name: rf_protocol
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- PAKETLER TAM SÜRÜME SABİTLENDİ (^ işareti yok) ---
  cupertino_icons: 1.0.2
  
  flutter_notification_listener:
    path: ./packages/flutter_notification_listener
  # Firebase ve Google Sign In (Eski, çalışan sürümler)
  firebase_core: 2.13.1
  firebase_auth: 4.6.2
  # KRİTİK: Tam olarak bu sürüm yüklenecek
  google_sign_in: 5.4.4
  cloud_firestore: 4.8.0
  
  google_fonts: ^6.1.0  # En son sürüm
  intl: 0.18.1
  uuid: 3.0.7
  lottie: 2.3.2
  font_awesome_flutter: 10.4.0

  # --- SENSÖR PAKETLERİ ---
  battery_plus: 4.0.1
  connectivity_plus: 4.0.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0

flutter:
  uses-material-design: true
  # --- DÜZELTME BURADA YAPILDI ---
  assets:
   - assets/google_logo.png # Tireden sonra boşluk eklendi