buildscript {
    ext {
        kotlin_version = '1.9.20'
    }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}

subprojects { subproject ->
    subproject.plugins.withId("com.android.application") {
        subproject.android {
            buildFeatures {
                buildConfig = true
            }
        }
    }
    subproject.plugins.withId("com.android.library") {
        subproject.android {
            buildFeatures {
                buildConfig = true
            }
        }
    }
}