// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw8kMsODeeyXPYBdCJ_ACj6WW8YHnTkwE',
    appId: '1:70654214962:web:61c3625d4b1f8415908d2b',
    messagingSenderId: '70654214962',
    projectId: 'redflag-protocol',
    authDomain: 'redflag-protocol.firebaseapp.com',
    storageBucket: 'redflag-protocol.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJLMLiasDF68SBDFSFJuLem5BSXD7QPZU',
    appId: '1:70654214962:android:959240b370b8695c908d2b',
    messagingSenderId: '70654214962',
    projectId: 'redflag-protocol',
    storageBucket: 'redflag-protocol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoBj63Geo83oqzMxg-Jby2-h56CoLDk3w',
    appId: '1:70654214962:ios:ba1fc6b4e74ed8ce908d2b',
    messagingSenderId: '70654214962',
    projectId: 'redflag-protocol',
    storageBucket: 'redflag-protocol.firebasestorage.app',
    androidClientId: '70654214962-085qgbjlev8tdi0j0m4lr2175di2s9mq.apps.googleusercontent.com',
    iosClientId: '70654214962-8jeqlsm2vcn8q4fnsr479p27rjbu994h.apps.googleusercontent.com',
    iosBundleId: 'com.example.rfProtocol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoBj63Geo83oqzMxg-Jby2-h56CoLDk3w',
    appId: '1:70654214962:ios:ba1fc6b4e74ed8ce908d2b',
    messagingSenderId: '70654214962',
    projectId: 'redflag-protocol',
    storageBucket: 'redflag-protocol.firebasestorage.app',
    androidClientId: '70654214962-085qgbjlev8tdi0j0m4lr2175di2s9mq.apps.googleusercontent.com',
    iosClientId: '70654214962-8jeqlsm2vcn8q4fnsr479p27rjbu994h.apps.googleusercontent.com',
    iosBundleId: 'com.example.rfProtocol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw8kMsODeeyXPYBdCJ_ACj6WW8YHnTkwE',
    appId: '1:70654214962:web:09204179cd8038ce908d2b',
    messagingSenderId: '70654214962',
    projectId: 'redflag-protocol',
    authDomain: 'redflag-protocol.firebaseapp.com',
    storageBucket: 'redflag-protocol.firebasestorage.app',
  );

}